export default [
  {
    description:
      "One breast and one leg, flame-grilled and infused with PERi-PERi. Served on the bone with crispy skin, in your choice of spice.",
    id: "item001",
    inStock: true,
    price: "6.75",
    title: "1/2 Chicken",
    type: "main",
  },
  {
    description:
      "Flame-grilled, infused with PERi-PERi and perfect for pairing with sides. Served on the bone with crispy skin, in your choice of spice.",
    id: "item002",
    inStock: true,
    price: "3.7",
    title: "1/4 Chicken",
    type: "main",
  },
  {
    description:
      "Flame-grilled, infused with PERi-PERi and served in your choice of spice. Cut into quarters and perfect with sides, it's great for sharing!",
    id: "item003",
    inStock: true,
    price: "12.0",
    title: "Whole Chicken",
    type: "main",
  },
  {
    description:
      "Flame-grilled with crispy skin. Infused with PERi-PERi and served in your choice of spice.",
    id: "item004",
    inStock: true,
    price: "6.95",
    title: "4 Boneless Thighs",
    type: "main",
  },
  {
    description:
      "Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a Portuguese Roll with lettuce, mayo and tomato.",
    id: "item005",
    inStock: true,
    price: "5.90",
    title: "Chicken Burger",
    type: "main",
  },
  {
    description:
      "Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a toasted pitta with lettuce, mayo, semi-dried PERi-tomatoes and cucumber.",
    id: "item006",
    inStock: true,
    price: "5.90",
    title: "Chicken Pitta",
    type: "main",
  },
  {
    description:
      "Chicken breast infused with PERi-PERi and grilled to your favourite spice. Served in a wrap with lettuce, lightly spiced yoghurt mayo and chilli jam.",
    id: "item007",
    inStock: true,
    price: "5.90",
    title: "Chicken Wrap",
    type: "main",
  },
  {
    description:
      "Two chicken breasts, flame-grilled with crispy skin. Infused with PERi-PERi and served in your choice of spice.",
    id: "item008",
    inStock: true,
    price: "7.25",
    title: "Butterfly Breast",
    type: "main",
  },
  {
    id: "item009",
    inStock: false,
    title: "Full Platter",
    price: "15.00",
    type: "main",
  },
  {
    id: "item010",
    inStock: false,
    title: "Family Platter",
    price: "15.00",
    type: "main",
  },
  {
    description:
      "A beanie patty made with cheddar cheese, chickpeas, sweetcorn, lentils, peas and pumpkin seeds. Served in a Portuguese Roll with lettuce, mayo and tomato.",
    id: "item011",
    inStock: true,
    price: "5.90",
    title: "Beanie Burger",
    type: "main",
  },
  {
    description:
      "A beanie patty made with cheddar cheese, chickpeas, sweetcorn, lentils, peas and pumpkin seeds. Served in a wrap with lettuce, lightly spiced yoghurt mayo and chilli jam.",
    id: "item012",
    inStock: true,
    price: "5.90",
    title: "Beanie Wrap",
    type: "main",
  },
  {
    description:
      "A beanie patty made with cheddar cheese, chickpeas, sweetcorn, lentils, peas and pumpkin seeds. Served in a toasted pitta with lettuce, mayo, semi-dried PERi-tomatoes and cucumber.",
    id: "item013",
    inStock: true,
    price: "5.90",
    title: "Beanie Pitta",
    type: "main",
  },
  {
    description:
      "Rich and indulgent chocolate between moist chocolate sponge drenched in rich chocolate.",
    id: "item014",
    inStock: true,
    price: "4.15",
    title: "Choco-Lot Cake",
    type: "dessert",
  },
  {
    description:
      "Rich and fluffy with walnuts, raisins and pineapple, topped with cream cheese icing.",
    id: "item015",
    inStock: true,
    price: "4.15",
    title: "Carrot Cake",
    type: "dessert",
  },
  {
    description:
      "Creamy cheesecake with fruity raspberry sauce on a crumbly biscuit base.",
    id: "item016",
    inStock: true,
    price: "4.15",
    title: "White Chocolate Cheesecake",
    type: "dessert",
  },
  {
    description:
      "A traditional Portuguese custard tart. Crispy and baked to perfection!",
    id: "item017",
    inStock: true,
    price: "1.70",
    title: "Naughty Nata",
    type: "dessert",
  },
  {
    description:
      "Rich chocolate brownie with a delicious hint of salted caramel.",
    id: "item018",
    inStock: true,
    price: "2.40",
    title: "Salted Caramel Brownie",
    type: "dessert",
  },
  {
    id: "item019",
    inStock: false,
    title: "Halloumi Sticks",
    price: "2.00",
    type: "starter",
  },
  {
    description:
      "Spicy mixed olives co-starring mushrooms, garlic and red pepper.",
    id: "item020",
    inStock: true,
    price: "3.25",
    title: "Spicy Mixed Olives",
    type: "starter",
  },
  {
    description:
      "Crunchy almonds, cashews and macadamia nuts in a fiery PERi-PERi seasoning.",
    id: "item021",
    inStock: true,
    price: "3.25",
    title: "PERi-PERi Nuts",
    type: "starter",
  },
  {
    description: "With warm pitta triangles. Great to share.",
    id: "item022",
    inStock: true,
    price: "3.45",
    title: "Houmous with PERi-PERi Drizzle",
    type: "starter",
  },
  {
    description: "Grilled for the perfect crunch!",
    id: "item023",
    inStock: true,
    price: "2.30",
    title: "Garlic Bread",
    type: "side",
  },
  {
    description: "Lightly spiced rice. One of our signature sides!",
    id: "item024",
    inStock: true,
    price: "2.30",
    title: "Spicy Rice",
    type: "side",
  },
  {
    description:
      "Packed full of crunchy chopped vegetables in a lightly spiced mayo.",
    id: "item025",
    inStock: true,
    price: "2.30",
    title: "Coleslaw",
    type: "side",
  },
  {
    description: "Creamy and comforting.",
    id: "item026",
    inStock: true,
    price: "2.30",
    title: "Creamy Mash",
    type: "side",
  },
  {
    description:
      "Crunchy, crisp and sweet. Flame-grilled and served with butter.",
    id: "item027",
    inStock: true,
    price: "2.30",
    title: "Corn on the Cob",
    type: "side",
  },
  {
    description: "Served in a garlic and lemon dressing.",
    id: "item028",
    inStock: true,
    price: "2.30",
    title: "Long Stem Broccoli",
    type: "side",
  },
  {
    description: "Crispy and delicious!",
    id: "item029",
    inStock: true,
    price: "2.30",
    title: "Chips",
    type: "side",
  },
  {
    description: "Crispy and sprinkled with PERi-PERi salt.",
    id: "item030",
    inStock: true,
    price: "2.30",
    title: "Peri Salted Chips",
    type: "side",
  },
  {
    description:
      "A mix of four leaves, sweet baby plum tomatoes and cucumber. Served with Balsamic dressing",
    id: "item031",
    inStock: true,
    price: "2.30",
    title: "Mixed Leaf Salad",
    type: "side",
  },
  {
    id: "item032",
    inStock: true,
    title: "Macho Peas",
    price: "2.25",
    type: "side",
  },
  {
    id: "item033",
    inStock: true,
    title: "Halloumi",
    price: "1.20",
    type: "extra",
  },
  {
    description:
      "Sweet and sticky with just a hint of spice. Great for dunking!",
    id: "item034",
    inStock: true,
    price: "0.55",
    title: "Chili Jam",
    type: "extra",
  },
  {
    description:
      "Creamy mayo infused with PERi-PERi. (Please note: PERinaise pots in our restaurants have slightly different ingredients to those sold in shops, so please check allergens before ordering).",
    id: "item035",
    inStock: true,
    price: "0.55",
    title: "Perinase",
    type: "extra",
  },
  {
    description: "Does what it says on the tin... say cheese!",
    id: "item036",
    inStock: true,
    price: "0.55",
    title: "Chedder Cheese",
    type: "extra",
  },
  {
    description: "Grilled Pineapple ring",
    id: "item037",
    inStock: true,
    price: "0.55",
    title: "Pineapple",
    type: "extra",
  },
  {
    description:
      "Flame-grilled, infused with PERi-PERi and perfect for pairing with sides. Served in your choice of spice.",
    id: "item038",
    inStock: true,
    price: "3.45",
    title: "3 Chicken Wings",
    type: "main",
  },
  {
    description:
      "Flame-grilled, infused with PERi-PERi and perfect for pairing with sides. Served in your choice of spice.",
    id: "item039",
    inStock: true,
    price: "5.2",
    title: "5 Chicken Wings",
    type: "main",
  },
  {
    description:
      "Flame-grilled, infused with PERi-PERi and perfect for pairing with sides. Served in your choice of spice.",
    id: "item040",
    inStock: true,
    price: "9.60",
    title: "10 Chicken Wings",
    type: "main",
  },
  {
    description:
      "A flame-grilled feast! Perfect for sharing and served in your choice of spice.",
    id: "item041",
    inStock: true,
    price: "12.20",
    title: "15 Chicken Wings",
    type: "main",
  },
  {
    description:
      "Rich and creamy caramel cheesecake on a crumbly biscuit base.",
    id: "item042",
    inStock: true,
    price: "4.15",
    title: "Gooey Caramel Cheesecake",
    type: "dessert",
  },
  {
    description:
      "330ml. Cool and refreshing! Berry flavoured iced tea infused with South African Rooibos. All natural flavours and caffeine free.",
    id: "item043",
    inStock: true,
    price: "2.45",
    title: "Rubro Berry",
    type: "drink",
  },
  {
    description:
      "330ml. Cool and refreshing! Berry flavoured iced tea infused with South African Rooibos. All natural flavours and caffeine free.",
    id: "item044",
    inStock: true,
    price: "2.45",
    title: "Rubro Lemon",
    type: "drink",
  },
  {
    description:
      "330ml. Cool and refreshing! Berry flavoured iced tea infused with South African Rooibos. All natural flavours and caffeine free.",
    id: "item045",
    inStock: true,
    price: "2.45",
    title: "Rubro Peach",
    type: "drink",
  },
  {
    description:
      "275ml. Sophisticated fizz with hints of rhubarb & white peach.",
    id: "item046",
    inStock: true,
    price: "2.85",
    title: "Kombucha Royal Flush",
    type: "drink",
  },
  {
    description:
      "330ml. Lightly sparking soft drink with a little cayenne for a happy pick me up!",
    id: "item047",
    inStock: true,
    price: "2.55",
    title: "KIX Cucumber Mint",
    type: "drink",
  },
  {
    description:
      "300ml. Clean, crisp and sparkling with organic Fairtrade ginger.",
    id: "item048",
    inStock: true,
    price: "2.55",
    title: "Gingerella",
    type: "drink",
  },
  {
    description: "ABV 0.5%, 330ml. With a light and limey citrus bite.",
    id: "item049",
    inStock: true,
    price: "3.45",
    title: "Big Drop Pale Ale",
    type: "drink",
  },
  {
    description: "As simple as it gets!",
    id: "item050",
    inStock: true,
    price: "2.10",
    title: "Still Mineral Water",
    type: "drink",
  },
  {
    description: "As simple as it gets! With a little Fizz",
    id: "item051",
    inStock: true,
    price: "2.10",
    title: "Sparkling Mineral Water",
    type: "drink",
  },
  {
    description: "250ml Because how else will we survive Simon",
    id: "item052",
    inStock: true,
    price: "5.45",
    title: "Cara Viva Summer Fruits",
    type: "drink",
  },
  {
    description: "Bottomless-A classic!",
    id: "item053",
    inStock: true,
    price: "2.80",
    title: "Coca-Cola Classic",
    type: "drink",
  },
  {
    description: "Bottomless",
    id: "item054",
    inStock: true,
    price: "2.60",
    title: "Diet Coke",
    type: "drink",
  },
  {
    description: "Bottomless",
    id: "item055",
    inStock: true,
    price: "2.60",
    title: "Coca-Cola Zero Sugar",
    type: "drink",
  },
  {
    description: "Bottomless",
    id: "item056",
    inStock: true,
    price: "2.60",
    title: "Sprite Zero",
    type: "drink",
  },
  {
    description: "Bottomless-Fruity fizz. Need we say more?",
    id: "item057",
    inStock: true,
    price: "2.60",
    title: "Fanta Orange",
    type: "drink",
  },
  {
    description: "Portugal's favourite golden larger",
    id: "item058",
    inStock: true,
    price: "3.95",
    title: "Sagres",
    type: "drink",
  },
  {
    description: "A pilsner with an up-to-date twist.",
    id: "item059",
    inStock: true,
    price: "3.95",
    title: "Freedom Pils",
    type: "drink",
  },
  {
    description: "A light and tropical extra pale ale.",
    id: "item060",
    inStock: true,
    price: "4.25",
    title: "Five Points XPA",
    type: "drink",
  },
  {
    description:
      "A carefully selected blend of whole pressed British apples, juicy raspberries and zesty limes provides an aromatic and deliciously refreshing real fruit cider with no artificial colours or flavours.",
    id: "item061",
    inStock: true,
    price: "4.85",
    title: "Rasberry & Lime Cider ABV 4%",
    type: "drink",
  },
  {
    description:
      "A carefully crafted blend of whole pressed British cider apples provides an authentic and deliciously refreshing real fruit cider with no artificial colours or flavours.",
    id: "item062",
    inStock: true,
    price: "4.85",
    title: "Benson's Apple Cider ABV 4%",
    type: "drink",
  },
  {
    description: "As simple as it gets!.",
    id: "item063",
    inStock: true,
    price: "0",
    title: "Glass of Water",
    type: "drink",
  },
];
